language: go
sudo: required
go:
  - "1.12"
services:
  - docker

env: GO111MODULE=on

before_script:
  go mod vendor

script:
  go test -race -cover -failfast ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)